class Translations {
  static const Map<String, Map<String, String>> _translations = {
    'fr': {
      'Bienvenue': 'Bienvenue',
      'Connectez_vous_pour_continuer': 'Connectez-vous pour continuer',
      'Email': 'Email',
      'Veuillez_entrer_votre_email': 'Veuillez entrer votre email',
      'Veuillez_entrer_un_email_valide': 'Veuillez entrer un email valide',
      'Mot_de_passe_oublie': 'Mot de passe oublié?',
      'Mot_de_passe': 'Mot de passe',
      'Veuillez_entrer_votre_mot_de_passe':
          'Veuillez entrer votre mot de passe',
      'Le_mot_de_passe_doit_contenir_au_moins_6_caractères':
          'Le mot de passe doit contenir au moins 6 caractères',
      'Se_connecter': 'Se connecter',
      'Continuer_avec_Google': 'Continuer avec Google',
      'Continuer_avec_Apple': 'Se connecter',
      'Pas_de_compte_sinscrire': 'Pas de compte? S\'inscrire',
      'Créer_un_compte': 'Créer un compte',
      'Rejoignez_nous_de_maintenant': 'Rejoignez-nous dès maintenant ',
      'Nom_complet': 'Nom complet',
      'Veuillez_entrer_votre_nom_complet': 'Veuillez entrer votre nom complet',
      'Numero_de_telephone': 'Numéro de téléphone',
      'Veuillez_entrer_votre_numéro_de_telephone':
          'Veuillez entrer votre numéro de téléphone',
      'Veuillez_entrer_un_numéro_de_telephone_valide':
          'Veuillez entrer un numéro de téléphone valide',
      'Ville': 'Ville',
      'Veuillez_sélectionner_une_ville': 'Veuillez sélectionner une ville',
      'Confirmer_le_mot_de_passe': 'Confirmer le mot de passe',
      'Veuillez_confirmer_votre_mot_de_passe':
          'Veuillez confirmer votre mot de passe',
      'Les_mots_de_passe_ne_correspondent_pas':
          'Les mots de passe ne correspondent pas',
      'Jaccepte_les': 'J\'accepte les ',
      'conditions_dutilisation': 'conditions d\'utilisation',
      'Conditions_d_utilisation': 'Conditions d\'utilisation',
      'Voici_le_texte_des_conditions_d_utilisation':
          'Voici le texte des conditions d\'utilisation...',
      'Sélectionner_la_langue_de_lapplication':
          'Sélectionner la langue de l\'application',
      'Langue': 'Langue',
      'Paramètres': 'Paramètres',
      'Notifications': 'Notifications',
      'Recevoir_des_notifications': 'Recevoir des notifications',
      'Theme': 'Thème',
      'Mode_sombre': 'Mode sombre',
      'Passer_en_mode_sombre': 'Passer en mode sombre',
      'Autres_options': 'Autres options',
      'Modifier_la_langue_de_lapplication':
          'Modifier la langue de l\'application',
      'Securite': 'Sécurité',
      'Modifier_votre_mot_de_passe': 'Modifier votre mot de passe',
      'Support': 'Support',
      'Contacter_le_support': 'Contacter le support',
      'Se_déconnecter': 'Se déconnecter',
      'Modifiez_votre_mot_de_passe_ou_configurez_vos_options_de_securité':
          'Modifiez votre mot de passe ou configurez vos options de sécurité.',
      'Changer_le_mot_de_passe': 'Changer le mot de passe',
      'Activer_la_vérification_en_deux_etapes':
          'Activer la vérification en deux étapes',
      'Historique_des_connexions': 'Historique des connexions',
      'Accédez_lassistance_et_a_laide_de_lapplication':
          'Accédez à l\'assistance et à l\'aide de l\'application',
      'FAQ': 'FAQ',
      'Signaler_un_problème': 'Signaler un problème',
      'sinscrire' : 'S\'inscrire',
      'DéjàuncompteSeconnecter' : 'Déjà un compte ? Se connecter',
      'politiquedeconfidentialite' : 'politique de confidentialité',

      'tableau_de_bord_du_prestataire' : 'Tableau de bord du prestataire',
      'total_des_service' : 'Total des services',
      'fonctionnalites_disponibles' : 'Fonctionnalites disponibles',
      'voir_mes_services' : 'Voir mes services',
      'notifications' : 'Notifications',

    },
    'en': {
      'Bienvenue': 'Welcome',
      'Connectez_vous_pour_continuer': 'Log in to continue',
      'Email': 'Email',
      'Veuillez_entrer_votre_email': 'Please enter your email',
      'Veuillez_entrer_un_email_valide': 'Please enter a valid email',
      'Mot_de_passe_oublie': 'Forgot password',
      'Mot_de_passe': 'Password',
      'Veuillez_entrer_votre_mot_de_passe': 'Please enter your password',
      'Le_mot_de_passe_doit_contenir_au_moins_6_caractères':
          'Password must be at least 6 characters',
      'Se_connecter': 'Log in',
      'Continuer_avec_Google': 'Continue with Google',
      'Continuer_avec_Apple': 'Continue with Apple',
      'Pas_de_compte_sinscrire': 'No account? Sign up',
      'Créer_un_compte': 'Create an account',
      'Rejoignez_nous_de_maintenant': 'Join us now',
      'Nom_complet': 'Full name',
      'Veuillez_entrer_votre_nom_complet': 'Please enter your full name',
      'Numero_de_telephone': 'Phone number',
      'Veuillez_entrer_votre_numéro_de_telephone':
          'Please enter your phone number',
      'Veuillez_entrer_un_numéro_de_telephone_valide':
          'Please enter a valid phone number',
      'Ville': 'City',
      'Veuillez_sélectionner_une_ville': 'Please select a city',
      'Confirmer_le_mot_de_passe': 'Confirm password',
      'Veuillez_confirmer_votre_mot_de_passe': 'Please confirm your password',
      'Les_mots_de_passe_ne_correspondent_pas': 'Passwords do not match',
      'Jaccepte_les': 'I accept the ',
      'conditions_dutilisation': 'terms of use',
      'Conditions_d_utilisation': 'Terms of use',
      'Voici_le_texte_des_conditions_d_utilisation':
          'Here is the text of the terms of use',
      'Sélectionner_la_langue_de_lapplication': 'Select the app language',
      'Langue': 'Language',
      'Paramètres': 'Settings',
      'Notifications': 'Notifications',
      'Recevoir_des_notifications': 'Receive notifications',
      'Theme': 'Theme',
      'Mode_sombre': 'Dark mode',
      'Passer_en_mode_sombre': 'Switch to dark mode',
      'Autres_options': 'Other options',
      'Modifier_la_langue_de_lapplication': 'Change application language',
      'Securite': 'Security',
      'Modifier_votre_mot_de_passe': 'Change your password',
      'Support': 'Support',
      'Contacter_le_support': 'Contact support',
      'Se_déconnecter': 'Log out',
      'Modifiez_votre_mot_de_passe_ou_configurez_vos_options_de_securité':
          'Change your password or configure your security options.',
      'Changer_le_mot_de_passe': 'Change password',
      'Activer_la_vérification_en_deux_etapes': 'Enable two-step verification',
      'Historique_des_connexions': 'Login history',
      'Accédez_lassistance_et_a_laide_de_lapplication':
          'Access application support and help',
      'FAQ': 'FAQ',
      'Signaler_un_problème': 'Report a problem',
      'sinscrire': 'Sign up',
  'DéjàuncompteSeconnecter': 'Already have an account? Log in',
  'politiquedeconfidentialite': 'Privacy policy',
    },
    'ar': {
      'Bienvenue': 'أهلاً وسهلاً',
      'Connectez_vous_pour_continuer': 'قم بتسجيل الدخول للمتابعة',
      'Email': 'البريد الإلكتروني',
      'Veuillez_entrer_votre_email': 'يرجى إدخال بريدك الإلكتروني',
      'Veuillez_entrer_un_email_valide': 'يرجى إدخال بريد إلكتروني صالح',
      'Mot_de_passe_oublie': 'نسيت كلمة المرور',
      'Mot_de_passe': 'كلمة المرور',
      'Veuillez_entrer_votre_mot_de_passe': 'يرجى إدخال كلمة المرور الخاصة بك',
      'Le_mot_de_passe_doit_contenir_au_moins_6_caractères':
          'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل',
      'Se_connecter': 'تسجيل الدخول',
      'Continuer_avec_Google': 'تابع باستخدام جوجل',
      'Continuer_avec_Apple': 'تابع باستخدام أبل',
      'Pas_de_compte_sinscrire': 'ليس لديك حساب؟ سجل الآن',
      'Créer_un_compte': 'إنشاء حساب',
      'Rejoignez_nous_de_maintenant': 'انضم إلينا الآن',
      'Nom_complet': 'الاسم الكامل',
      'Veuillez_entrer_votre_nom_complet': 'يرجى إدخال اسمك الكامل',
      'Numero_de_telephone': 'رقم الهاتف',
      'Veuillez_entrer_votre_numéro_de_telephone': 'يرجى إدخال رقم هاتفك',
      'Veuillez_entrer_un_numéro_de_telephone_valide':
          'يرجى إدخال رقم هاتف صالح',
      'Ville': 'المدينة',
      'Veuillez_sélectionner_une_ville': 'يرجى اختيار مدينة',
      'Confirmer_le_mot_de_passe': 'تأكيد كلمة المرور',
      'Veuillez_confirmer_votre_mot_de_passe': 'يرجى تأكيد كلمة المرور',
      'Les_mots_de_passe_ne_correspondent_pas': 'كلمات المرور غير متطابقة',
      'Jaccepte_les': 'أوافق على ',
      'conditions_dutilisation': 'شروط الاستخدام',
      'Conditions_d_utilisation': 'شروط الاستخدام',
      'Voici_le_texte_des_conditions_d_utilisation': 'إليك نص شروط الاستخدام',
      'Sélectionner_la_langue_de_lapplication': 'اختيار لغة التطبيق',
      'Langue': 'لغة',
      'Paramètres': 'الإعدادات',
      'Notifications': 'الإشعارات',
      'Recevoir_des_notifications': 'استلام الإشعارات',
      'Theme': 'الموضوع',
      'Mode_sombre': 'الوضع المظلم',
      'Passer_en_mode_sombre': 'الانتقال إلى الوضع المظلم',
      'Autres_options': 'خيارات أخرى',
      'Modifier_la_langue_de_lapplication': 'تغيير لغة التطبيق',
      'Securite': 'الأمان',
      'Modifier_votre_mot_de_passe': 'تغيير كلمة المرور',
      'Support': 'الدعم',
      'Contacter_le_support': 'اتصل بالدعم',
      'Se_déconnecter': 'تسجيل الخروج',
      'Modifiez_votre_mot_de_passe_ou_configurez_vos_options_de_securité':
          'قم بتغيير كلمة المرور الخاصة بك أو قم بتكوين خيارات الأمان الخاصة بك.',
      'Changer_le_mot_de_passe': 'تغيير كلمة المرور',
      'Activer_la_vérification_en_deux_etapes': 'تفعيل التحقق بخطوتين',
      'Historique_des_connexions': 'سجل تسجيل الدخول',
      'Accédez_lassistance_et_a_laide_de_lapplication':
          'الوصول إلى دعم ومساعدة التطبيق',
      'FAQ': 'الأسئلة الشائعة',
      'Signaler_un_problème': 'الإبلاغ عن مشكلة',
      'sinscrire': 'التسجيل',
  'DéjàuncompteSeconnecter': 'لديك حساب بالفعل؟ تسجيل الدخول',
  'politiquedeconfidentialite': 'سياسة الخصوصية',
    },
  };

  static String get(String key, String languageCode) {
    return _translations[languageCode]?[key] ?? key;
  }
}
